services:
  framewhat:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php-8.1/app
    volumes:
      - './:/var/www/html'
    networks:
      - net-framewhat

  nginx:
    image: nginx:1.22.0-alpine
    volumes:
      - './:/var/www/html'
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '${APP_PORT:-8000}:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - net-framewhat

  db:
    image: mysql/mysql-server:8.0
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        # MYSQL_ROOT_HOST: "%"
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - net-framewhat
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  net-framewhat:
    driver: bridge

volumes:
  mysql:
    driver: local
